### ISSUE TITLE
Sparklines or histograms?

### ISSUE THREAD

**Issue by kud1ing** [reugn/rspark#4]
Hi,

from the description i am under the impression this library produces [Histograms](https://en.wikipedia.org/wiki/Histogram#Examples) and not [Sparklines](https://en.wikipedia.org/wiki/Sparkline). Is that correct?

**Comment by reugn** [comment]
@kud1ing you're right, but that's how sparklines look in the terminal :). Also, this was the [original project](https://github.com/holman/spark) name.

**Comment by kud1ing** [comment]
I understand. A sparkline consists of a spark and a line. A histogram is not a sparkline.
Since you've already chosen a better(tm) programming language, maybe using a better name and description is an option also?
